#Franchise.delete_all
franchises = Franchise.create([
	{abbr: 'BAL', city: 'Baltimore', name: 'Orioles'},
	{abbr: 'BOS', city: 'Boston', name: 'Red Sox'},
	{abbr: 'CHW', city: 'Chicago', name: 'White Sox'},
	{abbr: 'CLE', city: 'Cleveland', name: 'Indians'},
	{abbr: 'DET', city: 'Detroit', name: 'Tigers'},
	{abbr: 'HOU', city: 'Houston', name: 'Astros'},
	{abbr: 'KCR', city: 'Kansas City', name: 'Royals'},
	{abbr: 'LAA', city: 'Los Angeles', name: 'Angels'},
	{abbr: 'MIN', city: 'Minnesota', name: 'Twins'},
	{abbr: 'NYY', city: 'New York', name: 'Yankees'},
	{abbr: 'OAK', city: 'Oakland', name: "A's"},
	{abbr: 'SEA', city: 'Seattle', name: 'Mariners'},
	{abbr: 'TBR', city: 'Tampa Bay', name: 'Rays'},
	{abbr: 'TEX', city: 'Texas', name: 'Rangers'},
	{abbr: 'TOR', city: 'Toronto', name: 'Blue Jays'},
	{abbr: 'ARI', city: 'Arizona', name: 'Diamondbacks'},
	{abbr: 'ATL', city: 'Atlanta', name: 'Braves'},
	{abbr: 'CHC', city: 'Chicago', name: 'Cubs'},
	{abbr: 'CIN', city: 'Cincinnati', name: 'Reds'},
	{abbr: 'COL', city: 'Colorado', name: 'Rockies'},
	{abbr: 'LAD', city: 'Los Angeles', name: 'Dodgers'},
	{abbr: 'MIA', city: 'Miami', name: 'Marlins'},
	{abbr: 'MIL', city: 'Milwaukee', name: 'Brewers'},
	{abbr: 'NYM', city: 'New York', name: 'Mets'},
	{abbr: 'PHI', city: 'Philadelphia', name: 'Phillies'},
	{abbr: 'PIT', city: 'Pittsburgh', name: 'Pirates'},
	{abbr: 'SDP', city: 'San Diego', name: 'Padres'},
	{abbr: 'SFG', city: 'San Francisco', name: 'Giants'},
	{abbr: 'STL', city: 'St. Louis', name: 'Cardinals'},
	{abbr: 'WAS', city: 'Washington', name: 'Nationals'},
])

#League.delete_all
leagues = League.create([
	{abbr: 'AL',  name: 'American League', level: 'MLB'},
	{abbr: 'NL',  name: 'National League', level: 'MLB'},
	{abbr: 'APP', name: 'Appalachian League', level: 'R'},
	{abbr: 'AFL', name: 'Arizona League', level: 'R'},
	{abbr: 'CAL', name: 'California League', level: 'A+'},
	{abbr: 'CAR', name: 'Carolina League', level: 'A+'},
	{abbr: 'DSL', name: 'Dominican Summer League', level: 'R'},
	{abbr: 'EAS', name: 'Eastern League', level: 'AA'},
	{abbr: 'FSL', name: 'Florida State League', level: 'A+'},
	{abbr: 'GCL', name: 'Gulf Coast League', level: 'R'},
	{abbr: 'INT', name: 'International League', level: 'AAA'},
	{abbr: 'MEX', name: 'Mexican League', level: 'AAA'},
	{abbr: 'MWL', name: 'Midwest League', level: 'A'},
	{abbr: 'NYP', name: 'New York-Penn League', level: 'A-SS'},
	{abbr: 'NWL', name: 'Northwest League', level: 'A-SS'},
	{abbr: 'PCL', name: 'Pacific Coast League', level: 'AAA'},
	{abbr: 'PIO', name: 'Pioneer League', level: 'R'},
	{abbr: 'SAL', name: 'South Atlantic League', level: 'A'},
	{abbr: 'SOU', name: 'Southern League', level: 'AA'},
	{abbr: 'TEX', name: 'Texas League', level: 'AA'},
	{abbr: 'VSL', name: 'Venezuelan Summer League', level: 'R'}
])
