StatDefinition.create([
	{code: 'p.w', name: 'Wins', abbr: 'W', raw: true, category: 'pitching'},
	{code: 'p.l', name: 'Losses', abbr: 'L', raw: true, category: 'pitching'},
	{code: 'p.wl%', name: 'Win-Loss Percentage', raw: false, category: 'pitching', format: "%.3f"},
	{code: 'p.era', name: 'Earned Run Average', raw: false, category: 'pitching', format: "%.3f"},
	{code: 'p.gp', name: 'Games Pitched', abbr: 'G', raw: true, category: 'pitching'},
	{code: 'p.gs', name: 'Games Started', abbr: 'GS', raw: true, category: 'pitching'},
	{code: 'p.gf', name: 'Games Finished', abbr: 'GF', raw: true, category: 'pitching'},
	{code: 'p.cg', name: 'Complete Games', abbr: 'CG', raw: true, category: 'pitching'},
	{code: 'p.sho', name: 'Shutouts', abbr: 'SHO', raw: true, category: 'pitching'},
	{code: 'p.sv', name: 'Saves', abbr: 'SV', raw: true, category: 'pitching'},
	{code: 'p.ip', name: 'Innings Pitched', abbr: 'IP', raw: true, category: 'pitching', format: "%.1f"},
	{code: 'p.h', name: 'Hits Allowed',  abbr: 'H', raw: true, category: 'pitching'},
	{code: 'p.r', name: 'Runs Allowed', abbr: 'R', raw: true, category: 'pitching'},
	{code: 'p.er', name: 'Earned Runs Allowed', abbr: 'ER', raw: true, category: 'pitching'},
	{code: 'p.hr', name: 'Home Runs Allowed', abbr: 'HR', raw: true, category: 'pitching'},
	{code: 'p.bb', name: 'Bases on Balls / Walks', abbr: 'BB', raw: true, category: 'pitching'},
	{code: 'p.ibb', name: 'Intentional Bases on Balls / Walks', abbr: 'IBB', raw: true, category: 'pitching'},
	{code: 'p.so', name: 'Strikeouts', abbr: 'SO', raw: true, category: 'pitching'},
	{code: 'p.hbp', name: 'Batters Hit by Pitch', abbr: 'HBP', raw: true, category: 'pitching'},
	{code: 'p.bk', name: 'Balks', abbr: 'BK', raw: true, category: 'pitching'},
	{code: 'p.wp', name: 'Wild Pitches', abbr: 'WP', raw: true, category: 'pitching'},
	{code: 'p.bf', name: 'Batters Faced', abbr: 'BF', raw: true, category: 'pitching'},
	{code: 'p.whip', name: 'Walks + Hits per Inning Pitched', abbr: 'WHIP', raw: false, category: 'pitching', format: "%.3f"},
	{code: 'p.h9', name: 'Hits per 9 Innings', abbr: 'H/9', raw: false, category: 'pitching', format: "%.1f}"},
	{code: 'p.hr9', name: 'Home Runs per 9 Innings', abbr: 'HR/9', raw: false, category: 'pitching', format: "%.1f"},
	{code: 'p.bb9', name: 'Walks per 9 Innings', abbr: 'BB/9', raw: false, category: 'pitching', format: "%.1f"},
	{code: 'p.so9', name: 'Strikeouts per 9 Innings', abbr: 'SO/9', raw: false, category: 'pitching', format: "%.1f"},
	{code: 'p.kbb', name: 'Strikeout-to-Walk Ratio', abbr: 'SO/BB', raw: false, category: 'pitching', format: "%.2f"},
	{code: 'b.gp', name: 'Games Played', abbr: 'G', raw: true, category: 'batting'},
	{code: 'b.pa', name: 'Plate Appearances', abbr: 'PA', raw: true, category: 'batting'},
	{code: 'b.ab', name: 'At-Bats', abbr: 'AB', raw: true, category: 'batting'},
	{code: 'b.r', name: 'Runs Scored', abbr: 'R', raw: true, category: 'batting'},
	{code: 'b.h', name: 'Hits', abbr: 'H', raw: true, category: 'batting'},
	{code: 'b.2b', name: 'Doubles', abbr: '2B', raw: true, category: 'batting'},
	{code: 'b.3b', name: 'Triples', abbr: '3B', raw: true, category: 'batting'},
	{code: 'b.hr', name: 'Home Runs', abbr: 'HR', raw: true, category: 'batting'},
	{code: 'b.rbi', name: 'Runs Batted In', abbr: 'RBI', raw: true, category: 'batting'},
	{code: 'b.bb', name: 'Bases on Balls / Walks', abbr: 'BB', raw: true, category: 'batting'},
	{code: 'b.so', name: 'Strikeouts', abbr: 'SO', raw: true, category: 'batting'},
	{code: 'b.ba', name: 'Batting Average', abbr: 'AVG', raw: false, category: 'batting', format: "%.3f"},
	{code: 'b.obp', name: 'On-Base Percentage', abbr: 'OBP', raw: false, category: 'batting', format: "%.3f"},
	{code: 'b.slg', name: 'Slugging Percentage', abbr: 'SLG', raw: false, category: 'batting', format: "%.3f"},
	{code: 'b.ops', name: 'On-Base Percentage', abbr: 'OPS', raw: false, category: 'batting', format: "%.3f"},
	{code: 'b.tb', name: 'Total Bases', abbr: 'TB', raw: false, category: 'batting', format: "%.3f"},
	{code: 'b.gdp', name: 'Grounded into Double Play', abbr: 'GDP', raw: true, category: 'batting'},
	{code: 'b.hbp', name: 'Hit By Pitch', abbr: 'HBP', raw: true, category: 'batting'},
	{code: 'b.sh', name: 'Sacrifice Hits', abbr: 'SH', raw: true, category: 'batting'},
	{code: 'b.sf', name: 'Sacrifice Flies', abbr: 'SF', raw: true, category: 'batting'},
	{code: 'b.ibb', name: 'Intentional Bases on Balls / Walks', abbr: 'IBB', raw: true, category: 'batting'}	
])

Franchise.create([
	{abbr: 'BAL', city: 'Baltimore', name: 'Orioles'},
	{abbr: 'BOS', city: 'Boston', name: 'Red Sox'},
	{abbr: 'CHW', city: 'Chicago', name: 'White Sox'},
	{abbr: 'CLE', city: 'Cleveland', name: 'Indians'},
	{abbr: 'DET', city: 'Detroit', name: 'Tigers'},
	{abbr: 'HOU', city: 'Houston', name: 'Astros'},
	{abbr: 'KCR', city: 'Kansas City', name: 'Royals'},
	{abbr: 'LAA', city: 'Los Angeles', name: 'Angels'},
	{abbr: 'MIN', city: 'Minnesota', name: 'Twins'},
	{abbr: 'NYY', city: 'New York', name: 'Yankees'},
	{abbr: 'OAK', city: 'Oakland', name: "A's"},
	{abbr: 'SEA', city: 'Seattle', name: 'Mariners'},
	{abbr: 'TBR', city: 'Tampa Bay', name: 'Rays'},
	{abbr: 'TEX', city: 'Texas', name: 'Rangers'},
	{abbr: 'TOR', city: 'Toronto', name: 'Blue Jays'},
	{abbr: 'ARI', city: 'Arizona', name: 'Diamondbacks'},
	{abbr: 'ATL', city: 'Atlanta', name: 'Braves'},
	{abbr: 'CHC', city: 'Chicago', name: 'Cubs'},
	{abbr: 'CIN', city: 'Cincinnati', name: 'Reds'},
	{abbr: 'COL', city: 'Colorado', name: 'Rockies'},
	{abbr: 'LAD', city: 'Los Angeles', name: 'Dodgers'},
	{abbr: 'MIA', city: 'Miami', name: 'Marlins'},
	{abbr: 'MIL', city: 'Milwaukee', name: 'Brewers'},
	{abbr: 'NYM', city: 'New York', name: 'Mets'},
	{abbr: 'PHI', city: 'Philadelphia', name: 'Phillies'},
	{abbr: 'PIT', city: 'Pittsburgh', name: 'Pirates'},
	{abbr: 'SDP', city: 'San Diego', name: 'Padres'},
	{abbr: 'SFG', city: 'San Francisco', name: 'Giants'},
	{abbr: 'STL', city: 'St. Louis', name: 'Cardinals'},
	{abbr: 'WAS', city: 'Washington', name: 'Nationals'},
])

#League.delete_all
League.create([
	{abbr: 'AL',  name: 'American League', level: 'MLB'},
	{abbr: 'NL',  name: 'National League', level: 'MLB'},
	{abbr: 'APP', name: 'Appalachian League', level: 'R'},
	{abbr: 'AFL', name: 'Arizona League', level: 'R'},
	{abbr: 'CAL', name: 'California League', level: 'A+'},
	{abbr: 'CAR', name: 'Carolina League', level: 'A+'},
	{abbr: 'DSL', name: 'Dominican Summer League', level: 'R'},
	{abbr: 'EAS', name: 'Eastern League', level: 'AA'},
	{abbr: 'FSL', name: 'Florida State League', level: 'A+'},
	{abbr: 'GCL', name: 'Gulf Coast League', level: 'R'},
	{abbr: 'INT', name: 'International League', level: 'AAA'},
	{abbr: 'MEX', name: 'Mexican League', level: 'AAA'},
	{abbr: 'MWL', name: 'Midwest League', level: 'A'},
	{abbr: 'NYP', name: 'New York-Penn League', level: 'A-SS'},
	{abbr: 'NWL', name: 'Northwest League', level: 'A-SS'},
	{abbr: 'PCL', name: 'Pacific Coast League', level: 'AAA'},
	{abbr: 'PIO', name: 'Pioneer League', level: 'R'},
	{abbr: 'SAL', name: 'South Atlantic League', level: 'A'},
	{abbr: 'SOU', name: 'Southern League', level: 'AA'},
	{abbr: 'TEX', name: 'Texas League', level: 'AA'},
	{abbr: 'VSL', name: 'Venezuelan Summer League', level: 'R'}
])

Team.create([
	{abbr: 'BAL', city: 'Baltimore', name: 'Orioles', franchise: Franchise.find_by_abbr('BAL'), league: League.find_by_abbr('AL')},
	{abbr: 'BOS', city: 'Boston', name: 'Red Sox', franchise: Franchise.find_by_abbr('BOS'), league: League.find_by_abbr('AL')},
	{abbr: 'CHW', city: 'Chicago', name: 'White Sox', franchise: Franchise.find_by_abbr('CHW'), league: League.find_by_abbr('AL')},
	{abbr: 'CLE', city: 'Cleveland', name: 'Indians', franchise: Franchise.find_by_abbr('CLE'), league: League.find_by_abbr('AL')},
	{abbr: 'DET', city: 'Detroit', name: 'Tigers', franchise: Franchise.find_by_abbr('DET'), league: League.find_by_abbr('AL')},
	{abbr: 'HOU', city: 'Houston', name: 'Astros', franchise: Franchise.find_by_abbr('HOU'), league: League.find_by_abbr('AL')},
	{abbr: 'KCR', city: 'Kansas City', name: 'Royals', franchise: Franchise.find_by_abbr('KCR'), league: League.find_by_abbr('AL')},
	{abbr: 'LAA', city: 'Los Angeles', name: 'Angels', franchise: Franchise.find_by_abbr('LAA'), league: League.find_by_abbr('AL')},
	{abbr: 'MIN', city: 'Minnesota', name: 'Twins', franchise: Franchise.find_by_abbr('MIN'), league: League.find_by_abbr('AL')},
	{abbr: 'NYY', city: 'New York', name: 'Yankees', franchise: Franchise.find_by_abbr('NYY'), league: League.find_by_abbr('AL')},
	{abbr: 'OAK', city: 'Oakland', name: "A's", franchise: Franchise.find_by_abbr('OAK'), league: League.find_by_abbr('AL')},
	{abbr: 'SEA', city: 'Seattle', name: 'Mariners', franchise: Franchise.find_by_abbr('SEA'), league: League.find_by_abbr('AL')},
	{abbr: 'TBR', city: 'Tampa Bay', name: 'Rays', franchise: Franchise.find_by_abbr('TAM'), league: League.find_by_abbr('AL')},
	{abbr: 'TEX', city: 'Texas', name: 'Rangers', franchise: Franchise.find_by_abbr('TEX'), league: League.find_by_abbr('AL')},
	{abbr: 'TOR', city: 'Toronto', name: 'Blue Jays', franchise: Franchise.find_by_abbr('TOR'), league: League.find_by_abbr('AL')},
	{abbr: 'ARI', city: 'Arizona', name: 'Diamondbacks', franchise: Franchise.find_by_abbr('ARI'), league: League.find_by_abbr('NL')},
	{abbr: 'ATL', city: 'Atlanta', name: 'Braves', franchise: Franchise.find_by_abbr('ATL'), league: League.find_by_abbr('NL')},
	{abbr: 'CHC', city: 'Chicago', name: 'Cubs', franchise: Franchise.find_by_abbr('CHC'), league: League.find_by_abbr('NL')},
	{abbr: 'CIN', city: 'Cincinnati', name: 'Reds', franchise: Franchise.find_by_abbr('CIN'), league: League.find_by_abbr('NL')},
	{abbr: 'COL', city: 'Colorado', name: 'Rockies', franchise: Franchise.find_by_abbr('COL'), league: League.find_by_abbr('NL')},
	{abbr: 'LAD', city: 'Los Angeles', name: 'Dodgers', franchise: Franchise.find_by_abbr('LAD'), league: League.find_by_abbr('NL')},
	{abbr: 'MIA', city: 'Miami', name: 'Marlins', franchise: Franchise.find_by_abbr('MIA'), league: League.find_by_abbr('NL')},
	{abbr: 'MIL', city: 'Milwaukee', name: 'Brewers', franchise: Franchise.find_by_abbr('MIL'), league: League.find_by_abbr('NL')},
	{abbr: 'NYM', city: 'New York', name: 'Mets', franchise: Franchise.find_by_abbr('NYM'), league: League.find_by_abbr('NL')},
	{abbr: 'PHI', city: 'Philadelphia', name: 'Phillies', franchise: Franchise.find_by_abbr('PHI'), league: League.find_by_abbr('NL')},
	{abbr: 'PIT', city: 'Pittsburgh', name: 'Pirates', franchise: Franchise.find_by_abbr('PIT'), league: League.find_by_abbr('NL')},
	{abbr: 'SDP', city: 'San Diego', name: 'Padres', franchise: Franchise.find_by_abbr('SDP'), league: League.find_by_abbr('NL')},
	{abbr: 'SFG', city: 'San Francisco', name: 'Giants', franchise: Franchise.find_by_abbr('SFG'), league: League.find_by_abbr('NL')},
	{abbr: 'STL', city: 'St. Louis', name: 'Cardinals', franchise: Franchise.find_by_abbr('STL'), league: League.find_by_abbr('NL')},
	{abbr: 'WAS', city: 'Washington', name: 'Nationals', franchise: Franchise.find_by_abbr('WAS'), league: League.find_by_abbr('NL')},
	{abbr: 'ABE', city: 'Aberdeen', name: 'IronBirds', franchise: Franchise.find_by_abbr('BAL'), league: League.find_by_abbr('NYP')},
	{abbr: 'AKR', city: 'Akron', name: 'Aeros', franchise: Franchise.find_by_abbr('CLE'), league: League.find_by_abbr('EAS')},
	{abbr: 'ALB', city: 'Albuquerque', name: 'Isotopes', franchise: Franchise.find_by_abbr('LAD'), league: League.find_by_abbr('PCL')},
	{abbr: 'ALT', city: 'Altoona', name: 'Curve', franchise: Franchise.find_by_abbr('PIT'), league: League.find_by_abbr('EAS')},
	{abbr: 'ARK', city: 'Arkansas', name: 'Travelers', franchise: Franchise.find_by_abbr('LAA'), league: League.find_by_abbr('TEX')},
	{abbr: 'ASH', city: 'Asheville', name: 'Tourists', franchise: Franchise.find_by_abbr('COL'), league: League.find_by_abbr('SAL')},
	{abbr: 'AUB', city: 'Auburn', name: 'Doubledays', franchise: Franchise.find_by_abbr('WAS'), league: League.find_by_abbr('NYP')},
	{abbr: 'AUG', city: 'Augusta', name: 'GreenJackets', franchise: Franchise.find_by_abbr('SFG'), league: League.find_by_abbr('SAL')},
	{abbr: 'BAK', city: 'Bakersfield', name: 'Blaze', franchise: Franchise.find_by_abbr('CIN'), league: League.find_by_abbr('CAL')},
	{abbr: 'BAT', city: 'Batavia', name: 'Muckdogs', franchise: Franchise.find_by_abbr('MIA'), league: League.find_by_abbr('NYP')},
	{abbr: 'BEL', city: 'Beloit', name: 'Snappers', franchise: Franchise.find_by_abbr('OAK'), league: League.find_by_abbr('MWL')},
	{abbr: 'BIL', city: 'Billings', name: 'Mustangs', franchise: Franchise.find_by_abbr('CIN'), league: League.find_by_abbr('PIO')},
	{abbr: 'BIN', city: 'Binghamton', name: 'Mets', franchise: Franchise.find_by_abbr('NYM'), league: League.find_by_abbr('EAS')},
	{abbr: 'BIR', city: 'Birmingham', name: 'Barons', franchise: Franchise.find_by_abbr('CHW'), league: League.find_by_abbr('SOU')},
	{abbr: 'BLU', city: 'Bluefield', name: 'Blue Jays', franchise: Franchise.find_by_abbr('TOR'), league: League.find_by_abbr('APP')},
	{abbr: 'BOI', city: 'Boise', name: 'Hawks', franchise: Franchise.find_by_abbr('CHC'), league: League.find_by_abbr('NWL')},
	{abbr: 'BOW', city: 'Bowie', name: 'BaySox', franchise: Franchise.find_by_abbr('BAL'), league: League.find_by_abbr('EAS')},
	{abbr: 'BGH', city: 'Bowling Green', name: 'Hot Rods', franchise: Franchise.find_by_abbr('TBR'), league: League.find_by_abbr('MWL')},
	{abbr: 'BRA', city: 'Bradenton', name: 'Marauders', franchise: Franchise.find_by_abbr('PIT'), league: League.find_by_abbr('FSL')},
	{abbr: 'BCM', city: 'Brevard County', name: 'Manatees', franchise: Franchise.find_by_abbr('MIL'), league: League.find_by_abbr('FSL')},
	{abbr: 'BRI', city: 'Bristol', name: 'White Sox', franchise: Franchise.find_by_abbr('CHW'), league: League.find_by_abbr('APP')},
	{abbr: 'BRO', city: 'Brooklyn', name: 'Cyclones', franchise: Franchise.find_by_abbr('NYM'), league: League.find_by_abbr('NYP')},
	{abbr: 'BUF', city: 'Buffalo', name: 'Bisons', franchise: Franchise.find_by_abbr('TOR'), league: League.find_by_abbr('INT')},
	{abbr: 'BUB', city: 'Burlington', name: 'Bees', franchise: Franchise.find_by_abbr('LAA'), league: League.find_by_abbr('MWL')},
	{abbr: 'BUR', city: 'Burlington', name: 'Royals', franchise: Franchise.find_by_abbr('KCR'), league: League.find_by_abbr('APP')},
	{abbr: 'CAR', city: 'Carolina', name: 'Mudcats', franchise: Franchise.find_by_abbr('CLE'), league: League.find_by_abbr('CAR')},
	{abbr: 'CRK', city: 'Cedar Rapids', name: 'Kernels', franchise: Franchise.find_by_abbr('MIN'), league: League.find_by_abbr('MWL')},
	{abbr: 'CHR', city: 'Charleston', name: 'RiverDogs', franchise: Franchise.find_by_abbr('NYY'), league: League.find_by_abbr('SAL')},
	{abbr: 'CHK', city: 'Charlotte', name: 'Knights', franchise: Franchise.find_by_abbr('CWS'), league: League.find_by_abbr('INT')},
	{abbr: 'CHS', city: 'Charlotte', name: 'Stone Crabs', franchise: Franchise.find_by_abbr('TBR'), league: League.find_by_abbr('FSL')},
	{abbr: 'CHL', city: 'Chattanooga', name: 'Lookouts', franchise: Franchise.find_by_abbr('LAD'), league: League.find_by_abbr('SOU')},
	{abbr: 'CLE', city: 'Clearwater', name: 'Threshers', franchise: Franchise.find_by_abbr('PHI'), league: League.find_by_abbr('FSL')},
	{abbr: 'CLI', city: 'Clinton', name: 'LumberKings', franchise: Franchise.find_by_abbr('SEA'), league: League.find_by_abbr('MWL')},
	{abbr: 'CSS', city: 'Colorado Springs', name: 'Sky Sox', franchise: Franchise.find_by_abbr('COL'), league: League.find_by_abbr('PCL')},
	{abbr: 'COC', city: 'Columbus', name: 'Clippers', franchise: Franchise.find_by_abbr('CLE'), league: League.find_by_abbr('INT')},
	{abbr: 'CON', city: 'Connecticut', name: 'Tigers', franchise: Franchise.find_by_abbr('DET'), league: League.find_by_abbr('NYP')},
	{abbr: 'CCH', city: 'Corpus Christi', name: 'Hooks', franchise: Franchise.find_by_abbr('HOU'), league: League.find_by_abbr('TEX')},
	{abbr: 'DAN', city: 'Danville', name: 'Braves', franchise: Franchise.find_by_abbr('ATL'), league: League.find_by_abbr('APP')},
	{abbr: 'DAD', city: 'Dayton', name: 'Dragons', franchise: Franchise.find_by_abbr('CIN'), league: League.find_by_abbr('MWL')},
	{abbr: 'DAC', city: 'Daytona', name: 'Cubs', franchise: Franchise.find_by_abbr('CHC'), league: League.find_by_abbr('FSL')},
	{abbr: 'DEL', city: 'Delmarva', name: 'Shorebirds', franchise: Franchise.find_by_abbr('BAL'), league: League.find_by_abbr('SAL')},
	{abbr: 'DUN', city: 'Dunedin', name: 'Blue Jays', franchise: Franchise.find_by_abbr('TOR'), league: League.find_by_abbr('FSL')},
	{abbr: 'DUR', city: 'Durham', name: 'Bulls', franchise: Franchise.find_by_abbr('TBR'), league: League.find_by_abbr('INT')},
	{abbr: 'ELI', city: 'Elizabethton', name: 'Twins', franchise: Franchise.find_by_abbr('MIN'), league: League.find_by_abbr('APP')},
	{abbr: 'ERI', city: 'Erie', name: 'SeaWolves', franchise: Franchise.find_by_abbr('DET'), league: League.find_by_abbr('EAS')},
	{abbr: 'EUG', city: 'Eugene', name: 'Emeralds', franchise: Franchise.find_by_abbr('SDP'), league: League.find_by_abbr('NWL')},
	{abbr: 'EVE', city: 'Everett', name: 'AquaSox', franchise: Franchise.find_by_abbr('SEA'), league: League.find_by_abbr('NWL')},
	{abbr: 'FMM', city: 'Fort Myers', name: 'Miracle', franchise: Franchise.find_by_abbr('MIN'), league: League.find_by_abbr('FSL')},
	{abbr: 'FWT', city: 'Fort Wayne', name: 'TinCaps', franchise: Franchise.find_by_abbr('SDP'), league: League.find_by_abbr('MWL')},
	{abbr: 'FRK', city: 'Frederick', name: 'Keys', franchise: Franchise.find_by_abbr('BAL'), league: League.find_by_abbr('CAR')},
	{abbr: 'FRG', city: 'Fresno', name: 'Grizzlies', franchise: Franchise.find_by_abbr('SFG'), league: League.find_by_abbr('PCL')},
	{abbr: 'FRI', city: 'Frisco', name: 'RoughRiders', franchise: Franchise.find_by_abbr('TEX'), league: League.find_by_abbr('TEX')},
	{abbr: 'GJR', city: 'Grand Junction', name: 'Roughriders', franchise: Franchise.find_by_abbr('COL'), league: League.find_by_abbr('PIO')},
	{abbr: 'GFV', city: 'Great Falls', name: 'Voyagers', franchise: Franchise.find_by_abbr('CHW'), league: League.find_by_abbr('PIO')},
	{abbr: 'GLL', city: 'Great Lakes', name: 'Loons', franchise: Franchise.find_by_abbr('LAD'), league: League.find_by_abbr('MWL')},
	{abbr: 'GRA', city: 'Greeneville', name: 'Astros', franchise: Franchise.find_by_abbr('HOU'), league: League.find_by_abbr('APP')},
	{abbr: 'GRG', city: 'Greensboro', name: 'Grasshoppers', franchise: Franchise.find_by_abbr('MIA'), league: League.find_by_abbr('SAL')},
	{abbr: 'GRD', city: 'Greeneville', name: 'Drive', franchise: Franchise.find_by_abbr('BOS'), league: League.find_by_abbr('SAL')},
	{abbr: 'GWI', city: 'Gwinnett', name: 'Braves', franchise: Franchise.find_by_abbr('ATL'), league: League.find_by_abbr('INT')},
	{abbr: 'HAG', city: 'Hagerstown', name: 'Suns', franchise: Franchise.find_by_abbr('WAS'), league: League.find_by_abbr('SAL')},
	{abbr: 'HAR', city: 'Harrisburg', name: 'Senators', franchise: Franchise.find_by_abbr('WAS'), league: League.find_by_abbr('EAS')},
	{abbr: 'HEL', city: 'Helena', name: 'Brewers', franchise: Franchise.find_by_abbr('MIL'), league: League.find_by_abbr('PIO')},
	{abbr: 'HIC', city: 'Hickory', name: 'Crawdads', franchise: Franchise.find_by_abbr('TEX'), league: League.find_by_abbr('SAL')},
	{abbr: 'HDM', city: 'High Desert', name: 'Mavericks', franchise: Franchise.find_by_abbr('SEA'), league: League.find_by_abbr('CAL')},
	{abbr: 'HIL', city: 'Hillsboro', name: 'Hops', franchise: Franchise.find_by_abbr('ARI'), league: League.find_by_abbr('NWL')},
	{abbr: 'HVR', city: 'Hudson Valley', name: 'Renegades', franchise: Franchise.find_by_abbr('TBR'), league: League.find_by_abbr('NYP')},
	{abbr: 'HUN', city: 'Huntsville', name: 'Stars', franchise: Franchise.find_by_abbr('MIL'), league: League.find_by_abbr('SOU')},
	{abbr: 'IFC', city: 'Idaho Falls', name: 'Chukars', franchise: Franchise.find_by_abbr('KCR'), league: League.find_by_abbr('PIO')},
	{abbr: 'IND', city: 'Indianapolis', name: 'Indians', franchise: Franchise.find_by_abbr('PIT'), league: League.find_by_abbr('INT')},
	{abbr: 'IES', city: 'Inland Empire', name: '66ers', franchise: Franchise.find_by_abbr('LAA'), league: League.find_by_abbr('CAL')},
	{abbr: 'IOW', city: 'Iowa', name: 'Cubs', franchise: Franchise.find_by_abbr('CHC'), league: League.find_by_abbr('PCL')},
	{abbr: 'JAG', city: 'Jackson', name: 'Generals', franchise: Franchise.find_by_abbr('SEA'), league: League.find_by_abbr('SOU')},
	{abbr: 'JAS', city: 'Jacksonville', name: 'Suns', franchise: Franchise.find_by_abbr('MIA'), league: League.find_by_abbr('SOU')},
	{abbr: 'JAM', city: 'Jamestown', name: 'Jammers', franchise: Franchise.find_by_abbr('PIT'), league: League.find_by_abbr('NYP')},
	{abbr: 'JCC', city: 'Johnson City', name: 'Cardinals', franchise: Franchise.find_by_abbr('STL'), league: League.find_by_abbr('APP')},
	{abbr: 'JUP', city: 'Jupiter', name: 'Hammerheads', franchise: Franchise.find_by_abbr('MIA'), league: League.find_by_abbr('FSL')},
	{abbr: 'KCC', city: 'Kane County', name: 'Cougars', franchise: Franchise.find_by_abbr('CHC'), league: League.find_by_abbr('MWL')},
	{abbr: 'KAN', city: 'Kannapolis', name: 'Intimidators', franchise: Franchise.find_by_abbr('CHW'), league: League.find_by_abbr('SAL')},
	{abbr: 'KIN', city: 'Kingsport', name: 'Mets', franchise: Franchise.find_by_abbr('NYM'), league: League.find_by_abbr('APP')},
	{abbr: 'LCC', city: 'Lake County', name: 'Captains', franchise: Franchise.find_by_abbr('CLE'), league: League.find_by_abbr('MWL')},
	{abbr: 'LES', city: 'Lake Elsinore', name: 'Storm', franchise: Franchise.find_by_abbr('SCP'), league: League.find_by_abbr('CAL')},
	{abbr: 'LFT', city: 'Lakeland', name: 'Flying Tigers', franchise: Franchise.find_by_abbr('DET'), league: League.find_by_abbr('FSL')},
	{abbr: 'LAK', city: 'Lakewood', name: 'BlueClaws', franchise: Franchise.find_by_abbr('PHI'), league: League.find_by_abbr('SAL')},
	{abbr: 'LAJ', city: 'Lancaster', name: 'JetHawks', franchise: Franchise.find_by_abbr('HOU'), league: League.find_by_abbr('CAL')},
	{abbr: 'LAL', city: 'Lansing', name: 'Lugnuts', franchise: Franchise.find_by_abbr('TOR'), league: League.find_by_abbr('MWL')},
	{abbr: 'LAV', city: 'Las Vegas', name: '51s', franchise: Franchise.find_by_abbr('NYM'), league: League.find_by_abbr('PCL')},
	{abbr: 'LVI', city: 'Lehigh Valley', name: 'IronPigs', franchise: Franchise.find_by_abbr('PHI'), league: League.find_by_abbr('INT')},
	{abbr: 'LEX', city: 'Lexington', name: 'Legends', franchise: Franchise.find_by_abbr('KCR'), league: League.find_by_abbr('SAL')},
	{abbr: 'LOU', city: 'Louisville', name: 'Bats', franchise: Franchise.find_by_abbr('CIN'), league: League.find_by_abbr('INT')},
	{abbr: 'LOW', city: 'Lowell', name: 'Spinners', franchise: Franchise.find_by_abbr('BOS'), league: League.find_by_abbr('NYP')},
	{abbr: 'LYN', city: 'Lynchburg', name: 'Hillcats', franchise: Franchise.find_by_abbr('ATL'), league: League.find_by_abbr('CAR')},
	{abbr: 'MVS', city: 'Mahoning Valley', name: 'Scrappers', franchise: Franchise.find_by_abbr('CLE'), league: League.find_by_abbr('NYP')},
	{abbr: 'MEM', city: 'Memphis', name: 'Redbirds', franchise: Franchise.find_by_abbr('STL'), league: League.find_by_abbr('PCL')},
	{abbr: 'MID', city: 'Midland', name: 'RockHounds', franchise: Franchise.find_by_abbr('OAK'), league: League.find_by_abbr('TEX')},
	{abbr: 'MIB', city: 'Mississippi', name: 'Braves', franchise: Franchise.find_by_abbr('ATL'), league: League.find_by_abbr('SOU')},
	{abbr: 'MIO', city: 'Missoula', name: 'Osprey', franchise: Franchise.find_by_abbr('ARI'), league: League.find_by_abbr('PIO')},
	{abbr: 'MOB', city: 'Mobile', name: 'BayBears', franchise: Franchise.find_by_abbr('ARI'), league: League.find_by_abbr('SOU')},
	{abbr: 'MOD', city: 'Modesto', name: 'Nuts', franchise: Franchise.find_by_abbr('COL'), league: League.find_by_abbr('CAL')},
	{abbr: 'MON', city: 'Montgomery', name: 'Biscuits', franchise: Franchise.find_by_abbr('TBR'), league: League.find_by_abbr('SOU')},
	{abbr: 'MBP', city: 'Myrtle Beach', name: 'Pelicans', franchise: Franchise.find_by_abbr('TEX'), league: League.find_by_abbr('CAR')},
	{abbr: 'NAS', city: 'Nashville', name: 'Sounds', franchise: Franchise.find_by_abbr('MIL'), league: League.find_by_abbr('PCL')},
	{abbr: 'NBR', city: 'New Britain', name: 'Rock Cats', franchise: Franchise.find_by_abbr('MIN'), league: League.find_by_abbr('EAS')},
	{abbr: 'NHF', city: 'New Hampshire', name: 'Fisher Cats', franchise: Franchise.find_by_abbr('TOR'), league: League.find_by_abbr('EAS')},
	{abbr: 'NOZ', city: 'New Orleans', name: 'Zephyrs', franchise: Franchise.find_by_abbr('MIA'), league: League.find_by_abbr('PCL')},
	{abbr: 'NOR', city: 'Norfolk', name: 'Tides', franchise: Franchise.find_by_abbr('BAL'), league: League.find_by_abbr('INT')},
	{abbr: 'NAN', city: 'Northwest Arkansas', name: 'Naturals', franchise: Franchise.find_by_abbr('KCR'), league: League.find_by_abbr('TEX')},
	{abbr: 'OGD', city: 'Ogden', name: 'Rapters', franchise: Franchise.find_by_abbr('LAD'), league: League.find_by_abbr('PIO')},
	{abbr: 'OCR', city: 'Oklahoma City', name: 'Redhawks', franchise: Franchise.find_by_abbr('HOU'), league: League.find_by_abbr('PCL')},
	{abbr: 'OMA', city: 'Omaha', name: 'Storm Chasers', franchise: Franchise.find_by_abbr('KCR'), league: League.find_by_abbr('PCL')},
	{abbr: 'ORE', city: 'Orem', name: 'Owlz', franchise: Franchise.find_by_abbr('LAA'), league: League.find_by_abbr('PIO')},
	{abbr: 'PBC', city: 'Palm Beach', name: 'Cardinals', franchise: Franchise.find_by_abbr('STL'), league: League.find_by_abbr('FSL')},
	{abbr: 'PAW', city: 'Pawtucket', name: 'Red Sox', franchise: Franchise.find_by_abbr('BOS'), league: League.find_by_abbr('INT')},
	{abbr: 'PEN', city: 'Pensacola', name: 'Blue Wahoos', franchise: Franchise.find_by_abbr('CIN'), league: League.find_by_abbr('SOU')},
	{abbr: 'PEO', city: 'Peoria', name: 'Chiefs', franchise: Franchise.find_by_abbr('STL'), league: League.find_by_abbr('MWL')},
	{abbr: 'POR', city: 'Portland', name: 'Sea Dogs', franchise: Franchise.find_by_abbr('BOS'), league: League.find_by_abbr('EAS')},
	{abbr: 'POT', city: 'Potomac', name: 'Nationals', franchise: Franchise.find_by_abbr('WAS'), league: League.find_by_abbr('CAR')},
	{abbr: 'PRI', city: 'Princeton', name: 'Rays', franchise: Franchise.find_by_abbr('TBR'), league: League.find_by_abbr('APP')},
	{abbr: 'PUL', city: 'Pulaski', name: 'Mariners', franchise: Franchise.find_by_abbr('SEA'), league: League.find_by_abbr('APP')},
	{abbr: 'QCR', city: 'Quad Cities', name: 'River Bandits', franchise: Franchise.find_by_abbr('HOU'), league: League.find_by_abbr('MWL')},
	{abbr: 'RCQ', city: 'Rancho Cucamonga', name: 'Quakes', franchise: Franchise.find_by_abbr('LAD'), league: League.find_by_abbr('CAL')},
	{abbr: 'REA', city: 'Reading', name: 'Fightin Phils', franchise: Franchise.find_by_abbr('PHI'), league: League.find_by_abbr('EAS')},
	{abbr: 'REN', city: 'Reno', name: 'Aces', franchise: Franchise.find_by_abbr('ARI'), league: League.find_by_abbr('PCL')},
	{abbr: 'RIC', city: 'Richmond', name: 'Flying Squirrels', franchise: Franchise.find_by_abbr('SFG'), league: League.find_by_abbr('EAS')},
	{abbr: 'ROC', city: 'Rochester', name: 'Red Wings', franchise: Franchise.find_by_abbr('MIN'), league: League.find_by_abbr('INT')},
	{abbr: 'ROM', city: 'Rome', name: 'Braves', franchise: Franchise.find_by_abbr('ATL'), league: League.find_by_abbr('SAL')},
	{abbr: 'RRE', city: 'Round Rock', name: 'Express', franchise: Franchise.find_by_abbr('TEX'), league: League.find_by_abbr('PCL')},
	{abbr: 'SAC', city: 'Sacramento', name: 'River Cats', franchise: Franchise.find_by_abbr('OAK'), league: League.find_by_abbr('PCL')},
	{abbr: 'SAL', city: 'Salem', name: 'Red Sox', franchise: Franchise.find_by_abbr('BOS'), league: League.find_by_abbr('CAR')},
	{abbr: 'SKV', city: 'Salem-Keizer', name: 'Volcanoes', franchise: Franchise.find_by_abbr('SFG'), league: League.find_by_abbr('NWL')},
	{abbr: 'SLB', city: 'Salt Lake', name: 'Bees', franchise: Franchise.find_by_abbr('LAA'), league: League.find_by_abbr('PCL')},
	{abbr: 'SAM', city: 'San Antonio', name: 'Missions', franchise: Franchise.find_by_abbr('SDP'), league: League.find_by_abbr('TEX')},
	{abbr: 'SJG', city: 'San Jose', name: 'Giants', franchise: Franchise.find_by_abbr('SFG'), league: League.find_by_abbr('CAL')},
	{abbr: 'SAV', city: 'Savannah', name: 'Sand Gnats', franchise: Franchise.find_by_abbr('NYM'), league: League.find_by_abbr('SAL')},
	{abbr: 'SWB', city: 'Scranton/Wilkes-Barre', name: 'RailRiders', franchise: Franchise.find_by_abbr('NYY'), league: League.find_by_abbr('INT')},
	{abbr: 'SBS', city: 'South Bend', name: 'Silver Hawks', franchise: Franchise.find_by_abbr('ARI'), league: League.find_by_abbr('MWL')},
	{abbr: 'SPO', city: 'Spokane', name: 'Indians', franchise: Franchise.find_by_abbr('TEX'), league: League.find_by_abbr('NWL')},
	{abbr: 'SPR', city: 'Springfield', name: 'Cardinals', franchise: Franchise.find_by_abbr('STL'), league: League.find_by_abbr('TEX')},
	{abbr: 'SLM', city: 'St. Lucie', name: 'Mets', franchise: Franchise.find_by_abbr('NYM'), league: League.find_by_abbr('FSL')},
	{abbr: 'SCS', city: 'State College', name: 'Spikes', franchise: Franchise.find_by_abbr('STL'), league: League.find_by_abbr('NYP')},
	{abbr: 'SIY', city: 'Staten Island', name: 'Yankees', franchise: Franchise.find_by_abbr('NYY'), league: League.find_by_abbr('NYP')},
	{abbr: 'STO', city: 'Stockton', name: 'Ports', franchise: Franchise.find_by_abbr('OAK'), league: League.find_by_abbr('CAL')},
	{abbr: 'SYR', city: 'Syracuse', name: 'Chiefs', franchise: Franchise.find_by_abbr('WAS'), league: League.find_by_abbr('INT')},
	{abbr: 'TAC', city: 'Tacoma', name: 'Rainiers', franchise: Franchise.find_by_abbr('SEA'), league: League.find_by_abbr('PCL')},
	{abbr: 'TAM', city: 'Tampa', name: 'Yankees', franchise: Franchise.find_by_abbr('NYY'), league: League.find_by_abbr('FSL')},
	{abbr: 'TEN', city: 'Tennessee', name: 'Smokies', franchise: Franchise.find_by_abbr('CHC'), league: League.find_by_abbr('SOU')},
	{abbr: 'TOL', city: 'Toledo', name: 'Mud Hens', franchise: Franchise.find_by_abbr('DET'), league: League.find_by_abbr('INT')},
	{abbr: 'TRE', city: 'Trenton', name: 'Thunder', franchise: Franchise.find_by_abbr('NYY'), league: League.find_by_abbr('EAS')},
	{abbr: 'TCD', city: 'Tri-City', name: 'Dust Devils', franchise: Franchise.find_by_abbr('COL'), league: League.find_by_abbr('NWL')},
	{abbr: 'TCV', city: 'Tri-City', name: 'ValleyCats', franchise: Franchise.find_by_abbr('HOU'), league: League.find_by_abbr('NYP')},
	{abbr: 'TUC', city: 'Tucson', name: 'Padres', franchise: Franchise.find_by_abbr('SDP'), league: League.find_by_abbr('PCL')},
	{abbr: 'TUL', city: 'Tulsa', name: 'Drillers', franchise: Franchise.find_by_abbr('COL'), league: League.find_by_abbr('TEX')},
	{abbr: 'VAN', city: 'Vancouver', name: 'Canadians', franchise: Franchise.find_by_abbr('TOR'), league: League.find_by_abbr('NWL')},
	{abbr: 'VER', city: 'Vermont', name: 'Lake Monsters', franchise: Franchise.find_by_abbr('OAK'), league: League.find_by_abbr('NYP')},
	{abbr: 'VIS', city: 'Visalia', name: 'Rawhide', franchise: Franchise.find_by_abbr('ARI'), league: League.find_by_abbr('CAL')},
	{abbr: 'WMW', city: 'West Michigan', name: 'Whitecaps', franchise: Franchise.find_by_abbr('DET'), league: League.find_by_abbr('MWL')},
	{abbr: 'WVP', city: 'West Virginia', name: 'Power', franchise: Franchise.find_by_abbr('PIT'), league: League.find_by_abbr('SAL')},
	{abbr: 'WIC', city: 'Williamsport', name: 'Crosscutters', franchise: Franchise.find_by_abbr('PHI'), league: League.find_by_abbr('NYP')},
	{abbr: 'WIB', city: 'Wilmington', name: 'Blue Rocks', franchise: Franchise.find_by_abbr('KCR'), league: League.find_by_abbr('CAR')},
	{abbr: 'WSD', city: 'Winston-Salem', name: 'Dash', franchise: Franchise.find_by_abbr('CHW'), league: League.find_by_abbr('CAR')},
	{abbr: 'WIS', city: 'Wisconsin', name: 'Timber Rattlers', franchise: Franchise.find_by_abbr('MIL'), league: League.find_by_abbr('MWL')},
])


#Mariners
f = Franchise.find_by_abbr('SEA')
sea = Team.find_by_abbr('SEA')
tac = Team.find_by_abbr('TAC')
jac = Team.find_by_abbr('JAG')

Player.create([
	{pid: 'cappsca01', franchise: f, team: sea, first_name: 'Carter', last_name: 'Capps', height: 77, weight: 210, bats: 'R', throws: 'R', position: 'RP', birth_date: Date.new(1990,8,7), on_25: true, on_40: true},
	{pid: 'iwakuhi01', franchise: f, team: sea, first_name: 'Hisashi', last_name: 'Iwakuma', height: 75, weight: 210, bats: 'R', throws: 'R', position: 'SP', birth_date: Date.new(1981,4,12), on_25:  true, on_40: true},
	{pid: 'maurebr01', franchise: f, team: sea, first_name: 'Brandon', last_name: 'Maurer', height: 77, weight: 215, bats: 'R', throws: 'R', position: 'SP,RP', birth_date: Date.new(1990,7,3), on_25: true, on_40: true},
	{pid: 'farquda01', franchise: f, team: sea, first_name: 'Danny', last_name: 'Farquhar', height: 69, weight: 180, bats: 'R', throws: 'R', position: 'RP', birth_date: Date.new(1987,2,17), on_25: true, on_40: true},
	{pid: 'ramirer01', franchise: f, team: sea, first_name: 'Erasmo', last_name: 'Ramirez', height: 71, weight: 200, bats: 'R', throws: 'R', position: 'SP', birth_date: Date.new(1990,5,2), on_25: true, on_40: true},
	{pid: 'furbuch01', franchise: f, team: sea, first_name: 'Charlie``', last_name: 'Furbush', height: 77, weight: 215, bats: 'L', throws: 'L', position: 'RP', birth_date: Date.new(1986,4,11), on_25: true, on_40: true},
	{pid: 'medinyo01', franchise: f, team: sea, first_name: 'Yoervis', last_name: 'Medina', height: 75, weight: 245, bats: 'R', throws: 'R', position: 'RP', birth_date: Date.new(1988,7,27), on_25: true, on_40: true},
	{pid: 'luetglu01', franchise: f, team: sea, first_name: 'Lucas', last_name: 'Luetge', height: 76, weight: 205, bats: 'L', throws: 'L', position: 'RP', birth_date: Date.new(1987,3,24), on_25: true, on_40: true},
	{pid: 'saundjo01', franchise: f, team: sea, first_name: 'Joe', last_name: 'Saunders', height: 75, weight: 215, bats: 'L', throws: 'L', position: 'SP', birth_date: Date.new(1981,6,16), on_25: true, on_40: true},
	{pid: 'perezol01', franchise: f, team: sea, first_name: 'Oliver', last_name: 'Perez', height: 75, weight: 220, bats: 'L', throws: 'L', position: 'RP', birth_date: Date.new(1981,8,15), on_25: true, on_40: true},
	{pid: 'haranaa01', franchise: f, team: sea, first_name: 'Aaron', last_name: 'Harang', height: 79, weight: 255, bats: 'R', throws: 'R', position: 'SP', birth_date: Date.new(1978,5,9), on_25: true, on_40: true},
	{pid: 'hernafe02', franchise: f, team: sea, first_name: 'Felix', last_name: 'Hernandez', height: 75, weight: 230, bats: 'R', throws: 'R', position: 'SP', birth_date: Date.new(1986,4,8), on_25: true, on_40: true},
	{pid: 'chaveen01', franchise: f, team: sea, first_name: 'Endy', last_name: 'Chavez', height: 71, weight: 170, bats: 'L', throws: 'L', position: 'OF', birth_date: Date.new(1978,2,7), on_25: true, on_40: true},
	{pid: 'quinthu01', franchise: f, team: sea, first_name: 'Humberto', last_name: 'Quintero', height: 69, weight: 215, bats: 'R', throws: 'R', position: 'C', birth_date: Date.new(1979,8,2), on_25: true, on_40: true},
	{pid: 'millebr01', franchise: f, team: sea, first_name: 'Brad', last_name: 'Miller', height: 74, weight: 185, bats: 'L', throws: 'R', position: 'SS', birth_date: Date.new(1989,8,18), on_25: true, on_40: true},
	{pid: 'frankni01', franchise: f, team: sea, first_name: 'Nick', last_name: 'Franklin', height: 73, weight: 195, bats: 'S', throws: 'R', position: '2B', birth_date: Date.new(1991,3,2), on_25: true, on_40: true},
	{pid: 'ibanera01', franchise: f, team: sea, first_name: 'Raul', last_name: 'Ibanez', height: 74, weight: 225, bats: 'L', throws: 'R', position: 'LF', birth_date: Date.new(1972,6,2), on_25: true, on_40: true},
	{pid: 'ackledu01', franchise: f, team: sea, first_name: 'Dustin', last_name: 'Ackley', height: 73, weight: 195, bats: 'L', throws: 'R', position: '2B,OF', birth_date: Date.new(1988,2,26), on_25: true, on_40: true},
	{pid: 'seageky01', franchise: f, team: sea, first_name: 'Kyle', last_name: 'Seager', height: 72, weight: 215, bats: 'L', throws: 'R', position: '3B', birth_date: Date.new(1987,11,3), on_25: true, on_40: true},
	{pid: 'morsemi01', franchise: f, team: sea, first_name: 'Mike', last_name: 'Morse', height: 77, weight: 245, bats: 'R', throws: 'R', position: 'OF,DH', birth_date: Date.new(1982,3,22), on_25: true, on_40: true},
	{pid: 'blanche01', franchise: f, team: sea, first_name: 'Henry', last_name: 'Blanco', height: 71, weight: 220, bats: 'R', throws: 'R', position: 'C', birth_date: Date.new(1971,8,29), on_25: true, on_40: true},
	{pid: 'moralke01', franchise: f, team: sea, first_name: 'Kendrys', last_name: 'Morales', height: 73, weight: 220, bats: 'S', throws: 'R', position: 'DH,1B', birth_date: Date.new(1983,6,20), on_25: true, on_40: true},
	{pid: 'ryanbr01',  franchise: f, team: sea, first_name: 'Brendan', last_name: 'Ryan', height: 74, weight: 195, bats: 'R', throws: 'R', position: 'SS', birth_date: Date.new(1982,3,26), on_25: true, on_40: true},
	{pid: 'smoakju01', franchise: f, team: sea, first_name: 'Justin', last_name: 'Smoak', height: 76, weight: 220, bats: 'S', throws: 'L', position: '1B', birth_date: Date.new(1986,12,5), on_25: true, on_40: true},
	{pid: 'saundmi01', franchise: f, team: sea, first_name: 'Michael', last_name: 'Saunders', height: 76, weight: 225, bats: 'L', throws: 'R', position: 'OF', birth_date: Date.new(1986,11,19), on_25: true, on_40: true},
	{pid: 'ruffich02', franchise: f, team: tac, first_name: 'Chance', last_name: 'Ruffin', height: 72, weight: 195, bats: 'R', throws: 'R', position: 'RP', birth_date: Date.new(1988,9,8), on_25: false, on_40: true},
	{pid: 'wilheto01', franchise: f, team: tac, first_name: 'Tom', last_name: 'Wilhelmsen', height: 78, weight: 220, bats: 'R', throws: 'R', position: 'RP', birth_date: Date.new(1983,12,16), on_25: false, on_40: true},
	{pid: 'pryorst01', franchise: f, team: nil, first_name: 'Stephen', last_name: 'Pryor', height: 76, weight: 250, bats: 'R', throws: 'R', position: 'RP', birth_date: Date.new(1989,7,23), on_25: false, on_40: true, on_dl: true},
	{pid: 'noesihe01', franchise: f, team: tac, first_name: 'Hector', last_name: 'Noesi', height: 75, weight: 205, bats: 'R', throws: 'R', position: 'SP,RP', birth_date: Date.new(1987,1,26), on_25: false, on_40: true},
	{pid: 'hultzda01', franchise: f, team: nil, first_name: 'Danny', last_name: 'Hultzen', height: 75, weight: 200, bats: 'L', throws: 'L', position: 'SP', birth_date: Date.new(1989,11,28), on_25: false, on_40: true, on_dl: true},
	{pid: 'lafrobo01', franchise: f, team: tac, first_name: 'Bobby', last_name: 'LaFromboise', height: 76, weight: 215, bats: 'L', throws: 'L', position: 'RP', birth_date: Date.new(1986,6,25), on_25: false, on_40: true},
	{pid: 'beavabl01', franchise: f, team: tac, first_name: 'Blake', last_name: 'Beavan', height: 79, weight: 255, bats: 'R', throws: 'R', position: 'SP,RP', birth_date: Date.new(1989,1,17), on_25: false, on_40: true},
	{pid: 'fernaan02', franchise: f, team: jac, first_name: 'Anthony', last_name: 'Fernandez', height: 76, weight: 210, bats: 'L', throws: 'L', position: 'SP,RP', birth_date: Date.new(1990,6,8), on_25: false, on_40: true},
	{pid: 'triunca01', franchise: f, team: tac, first_name: 'Carlos', last_name: 'Triunfel', height: 71, weight: 205, bats: 'R', throws: 'R', position: '2B,SS', birth_date: Date.new(1990,2,27), on_25: false, on_40: true},
	{pid: 'morbaju01', franchise: f, team: jac, first_name: 'Julio', last_name: 'Morban', height: 73, weight: 205, bats: 'L', throws: 'L', position: 'OF', birth_date: Date.new(1992,2,13), on_25: false, on_40: true},
	{pid: 'zuninmi01', franchise: f, team: nil, first_name: 'Mike', last_name: 'Zunino', height: 74, weight: 220, bats: 'R', throws: 'R', position: 'C', birth_date: Date.new(1991,3,25), on_25: false, on_40: true, on_dl: true},
	{pid: 'pegueca01', franchise: f, team: tac, first_name: 'Carlos', last_name: 'Peguero', height: 77, weight: 255, bats: 'L', throws: 'L', position: 'OF', birth_date: Date.new(1987,2,22), on_25: true, on_40: true},
	{pid: 'sucreje01', franchise: f, team: nil, first_name: 'Jesus', last_name: 'Sucre', height: 72, weight: 225, bats: 'R', throws: 'R', position: 'C', birth_date: Date.new(1988,4,30), on_25: false, on_40: true, on_dl: true},
	{pid: 'monteje01', franchise: f, team: nil, first_name: 'Jesus', last_name: 'Montero', height: 73, weight: 230, bats: 'R', throws: 'R', position: 'C', birth_date: Date.new(1989,11,28), on_25: false, on_40: true, suspended: true},
	{pid: 'gutiefr01', franchise: f, team: nil, first_name: 'Franklin', last_name: 'Gutierrez', height: 74, weight: 195, bats: 'R', throws: 'R', position: 'CF', birth_date: Date.new(1983,2,21), on_25: false, on_40: true, on_dl: true},
])

Stat.delete_all
p = Player.find_by_pid("millebr01")
Stat.create([
	{player: p, team: Team.find_by_abbr('CLI'), season: 2011, stint: 1, stat_definition: StatDefinition.find_by_code('b.gp'), value: 14},
	{player: p, team: Team.find_by_abbr('CLI'), season: 2011, stint: 1, stat_definition: StatDefinition.find_by_code('b.pa'), value: 59},
	{player: p, team: Team.find_by_abbr('CLI'), season: 2011, stint: 1, stat_definition: StatDefinition.find_by_code('b.ab'), value: 53},
	{player: p, team: Team.find_by_abbr('CLI'), season: 2011, stint: 1, stat_definition: StatDefinition.find_by_code('b.r'), value: 9},
	{player: p, team: Team.find_by_abbr('CLI'), season: 2011, stint: 1, stat_definition: StatDefinition.find_by_code('b.h'), value: 22},
	{player: p, team: Team.find_by_abbr('CLI'), season: 2011, stint: 1, stat_definition: StatDefinition.find_by_code('b.2b'), value: 4},
	{player: p, team: Team.find_by_abbr('CLI'), season: 2011, stint: 1, stat_definition: StatDefinition.find_by_code('b.3b'), value: 1},
	{player: p, team: Team.find_by_abbr('CLI'), season: 2011, stint: 1, stat_definition: StatDefinition.find_by_code('b.hr'), value: 0},
	{player: p, team: Team.find_by_abbr('CLI'), season: 2011, stint: 1, stat_definition: StatDefinition.find_by_code('b.rbi'), value: 7},
	{player: p, team: Team.find_by_abbr('CLI'), season: 2011, stint: 1, stat_definition: StatDefinition.find_by_code('b.so'), value: 9},
	{player: p, team: Team.find_by_abbr('CLI'), season: 2011, stint: 1, stat_definition: StatDefinition.find_by_code('b.bb'), value: 4},
	{player: p, team: Team.find_by_abbr('CLI'), season: 2011, stint: 1, stat_definition: StatDefinition.find_by_code('b.gdp'), value: 1},
	{player: p, team: Team.find_by_abbr('CLI'), season: 2011, stint: 1, stat_definition: StatDefinition.find_by_code('b.hbp'), value: 1},
	{player: p, team: Team.find_by_abbr('CLI'), season: 2011, stint: 1, stat_definition: StatDefinition.find_by_code('b.sh'), value: 0},
	{player: p, team: Team.find_by_abbr('CLI'), season: 2011, stint: 1, stat_definition: StatDefinition.find_by_code('b.sf'), value: 1},
	{player: p, team: Team.find_by_abbr('CLI'), season: 2011, stint: 1, stat_definition: StatDefinition.find_by_code('b.ibb'), value: 0},

	{player: p, team: Team.find_by_abbr('HDM'), season: 2012, stint: 1, stat_definition: StatDefinition.find_by_code('b.gp'), value: 97},
	{player: p, team: Team.find_by_abbr('HDM'), season: 2012, stint: 1, stat_definition: StatDefinition.find_by_code('b.pa'), value: 473},
	{player: p, team: Team.find_by_abbr('HDM'), season: 2012, stint: 1, stat_definition: StatDefinition.find_by_code('b.ab'), value: 410},
	{player: p, team: Team.find_by_abbr('HDM'), season: 2012, stint: 1, stat_definition: StatDefinition.find_by_code('b.r'), value: 89},
	{player: p, team: Team.find_by_abbr('HDM'), season: 2012, stint: 1, stat_definition: StatDefinition.find_by_code('b.h'), value: 139},
	{player: p, team: Team.find_by_abbr('HDM'), season: 2012, stint: 1, stat_definition: StatDefinition.find_by_code('b.2b'), value: 33},
	{player: p, team: Team.find_by_abbr('HDM'), season: 2012, stint: 1, stat_definition: StatDefinition.find_by_code('b.3b'), value: 5},
	{player: p, team: Team.find_by_abbr('HDM'), season: 2012, stint: 1, stat_definition: StatDefinition.find_by_code('b.hr'), value: 11},
	{player: p, team: Team.find_by_abbr('HDM'), season: 2012, stint: 1, stat_definition: StatDefinition.find_by_code('b.rbi'), value: 56},
	{player: p, team: Team.find_by_abbr('HDM'), season: 2012, stint: 1, stat_definition: StatDefinition.find_by_code('b.so'), value: 79},
	{player: p, team: Team.find_by_abbr('HDM'), season: 2012, stint: 1, stat_definition: StatDefinition.find_by_code('b.bb'), value: 52},
	{player: p, team: Team.find_by_abbr('HDM'), season: 2012, stint: 1, stat_definition: StatDefinition.find_by_code('b.gdp'), value: 5},
	{player: p, team: Team.find_by_abbr('HDM'), season: 2012, stint: 1, stat_definition: StatDefinition.find_by_code('b.hbp'), value: 2},
	{player: p, team: Team.find_by_abbr('HDM'), season: 2012, stint: 1, stat_definition: StatDefinition.find_by_code('b.sh'), value: 4},
	{player: p, team: Team.find_by_abbr('HDM'), season: 2012, stint: 1, stat_definition: StatDefinition.find_by_code('b.sf'), value: 5},
	{player: p, team: Team.find_by_abbr('HDM'), season: 2012, stint: 1, stat_definition: StatDefinition.find_by_code('b.ibb'), value: 2},

	{player: p, team: Team.find_by_abbr('JAG'), season: 2012, stint: 2, stat_definition: StatDefinition.find_by_code('b.gp'), value: 40},
	{player: p, team: Team.find_by_abbr('JAG'), season: 2012, stint: 2, stat_definition: StatDefinition.find_by_code('b.pa'), value: 170},
	{player: p, team: Team.find_by_abbr('JAG'), season: 2012, stint: 2, stat_definition: StatDefinition.find_by_code('b.ab'), value: 147},
	{player: p, team: Team.find_by_abbr('JAG'), season: 2012, stint: 2, stat_definition: StatDefinition.find_by_code('b.r'), value: 21},
	{player: p, team: Team.find_by_abbr('JAG'), season: 2012, stint: 2, stat_definition: StatDefinition.find_by_code('b.h'), value: 47},
	{player: p, team: Team.find_by_abbr('JAG'), season: 2012, stint: 2, stat_definition: StatDefinition.find_by_code('b.2b'), value: 7},
	{player: p, team: Team.find_by_abbr('JAG'), season: 2012, stint: 2, stat_definition: StatDefinition.find_by_code('b.3b'), value: 2},
	{player: p, team: Team.find_by_abbr('JAG'), season: 2012, stint: 2, stat_definition: StatDefinition.find_by_code('b.hr'), value: 4},
	{player: p, team: Team.find_by_abbr('JAG'), season: 2012, stint: 2, stat_definition: StatDefinition.find_by_code('b.rbi'), value: 12},
	{player: p, team: Team.find_by_abbr('JAG'), season: 2012, stint: 2, stat_definition: StatDefinition.find_by_code('b.so'), value: 26},
	{player: p, team: Team.find_by_abbr('JAG'), season: 2012, stint: 2, stat_definition: StatDefinition.find_by_code('b.bb'), value: 22},
	{player: p, team: Team.find_by_abbr('JAG'), season: 2012, stint: 2, stat_definition: StatDefinition.find_by_code('b.gdp'), value: 4},
	{player: p, team: Team.find_by_abbr('JAG'), season: 2012, stint: 2, stat_definition: StatDefinition.find_by_code('b.hbp'), value: 0},
	{player: p, team: Team.find_by_abbr('JAG'), season: 2012, stint: 2, stat_definition: StatDefinition.find_by_code('b.sh'), value: 0},
	{player: p, team: Team.find_by_abbr('JAG'), season: 2012, stint: 2, stat_definition: StatDefinition.find_by_code('b.sf'), value: 1},
	{player: p, team: Team.find_by_abbr('JAG'), season: 2012, stint: 2, stat_definition: StatDefinition.find_by_code('b.ibb'), value: 0},
	
	{player: p, team: Team.find_by_abbr('JAG'), season: 2013, stint: 1, stat_definition: StatDefinition.find_by_code('b.gp'), value: 42},
	{player: p, team: Team.find_by_abbr('JAG'), season: 2013, stint: 1, stat_definition: StatDefinition.find_by_code('b.pa'), value: 175},
	{player: p, team: Team.find_by_abbr('JAG'), season: 2013, stint: 1, stat_definition: StatDefinition.find_by_code('b.ab'), value: 153},
	{player: p, team: Team.find_by_abbr('JAG'), season: 2013, stint: 1, stat_definition: StatDefinition.find_by_code('b.r'), value: 27},
	{player: p, team: Team.find_by_abbr('JAG'), season: 2013, stint: 1, stat_definition: StatDefinition.find_by_code('b.h'), value: 45},
	{player: p, team: Team.find_by_abbr('JAG'), season: 2013, stint: 1, stat_definition: StatDefinition.find_by_code('b.2b'), value: 7},
	{player: p, team: Team.find_by_abbr('JAG'), season: 2013, stint: 1, stat_definition: StatDefinition.find_by_code('b.3b'), value: 1},
	{player: p, team: Team.find_by_abbr('JAG'), season: 2013, stint: 1, stat_definition: StatDefinition.find_by_code('b.hr'), value: 6},
	{player: p, team: Team.find_by_abbr('JAG'), season: 2013, stint: 1, stat_definition: StatDefinition.find_by_code('b.rbi'), value: 25},
	{player: p, team: Team.find_by_abbr('JAG'), season: 2013, stint: 1, stat_definition: StatDefinition.find_by_code('b.so'), value: 30},
	{player: p, team: Team.find_by_abbr('JAG'), season: 2013, stint: 1, stat_definition: StatDefinition.find_by_code('b.bb'), value: 20},
	{player: p, team: Team.find_by_abbr('JAG'), season: 2013, stint: 1, stat_definition: StatDefinition.find_by_code('b.gdp'), value: 1},
	{player: p, team: Team.find_by_abbr('JAG'), season: 2013, stint: 1, stat_definition: StatDefinition.find_by_code('b.hbp'), value: 1},
	{player: p, team: Team.find_by_abbr('JAG'), season: 2013, stint: 1, stat_definition: StatDefinition.find_by_code('b.sh'), value: 1},
	{player: p, team: Team.find_by_abbr('JAG'), season: 2013, stint: 1, stat_definition: StatDefinition.find_by_code('b.sf'), value: 0},
	{player: p, team: Team.find_by_abbr('JAG'), season: 2013, stint: 1, stat_definition: StatDefinition.find_by_code('b.ibb'), value: 2},
	
	{player: p, team: Team.find_by_abbr('TAC'), season: 2013, stint: 2, stat_definition: StatDefinition.find_by_code('b.gp'), value: 26},
	{player: p, team: Team.find_by_abbr('TAC'), season: 2013, stint: 2, stat_definition: StatDefinition.find_by_code('b.pa'), value: 122},
	{player: p, team: Team.find_by_abbr('TAC'), season: 2013, stint: 2, stat_definition: StatDefinition.find_by_code('b.ab'), value: 104},
	{player: p, team: Team.find_by_abbr('TAC'), season: 2013, stint: 2, stat_definition: StatDefinition.find_by_code('b.r'), value: 26},
	{player: p, team: Team.find_by_abbr('TAC'), season: 2013, stint: 2, stat_definition: StatDefinition.find_by_code('b.h'), value: 37},
	{player: p, team: Team.find_by_abbr('TAC'), season: 2013, stint: 2, stat_definition: StatDefinition.find_by_code('b.2b'), value: 5},
	{player: p, team: Team.find_by_abbr('TAC'), season: 2013, stint: 2, stat_definition: StatDefinition.find_by_code('b.3b'), value: 1},
	{player: p, team: Team.find_by_abbr('TAC'), season: 2013, stint: 2, stat_definition: StatDefinition.find_by_code('b.hr'), value: 6},
	{player: p, team: Team.find_by_abbr('TAC'), season: 2013, stint: 2, stat_definition: StatDefinition.find_by_code('b.rbi'), value: 28},
	{player: p, team: Team.find_by_abbr('TAC'), season: 2013, stint: 2, stat_definition: StatDefinition.find_by_code('b.so'), value: 18},
	{player: p, team: Team.find_by_abbr('TAC'), season: 2013, stint: 2, stat_definition: StatDefinition.find_by_code('b.bb'), value: 15},
	{player: p, team: Team.find_by_abbr('TAC'), season: 2013, stint: 2, stat_definition: StatDefinition.find_by_code('b.gdp'), value: 0},
	{player: p, team: Team.find_by_abbr('TAC'), season: 2013, stint: 2, stat_definition: StatDefinition.find_by_code('b.hbp'), value: 0},
	{player: p, team: Team.find_by_abbr('TAC'), season: 2013, stint: 2, stat_definition: StatDefinition.find_by_code('b.sh'), value: 0},
	{player: p, team: Team.find_by_abbr('TAC'), season: 2013, stint: 2, stat_definition: StatDefinition.find_by_code('b.sf'), value: 3},
	{player: p, team: Team.find_by_abbr('TAC'), season: 2013, stint: 2, stat_definition: StatDefinition.find_by_code('b.ibb'), value: 0},
	
	{player: p, team: Team.find_by_abbr('SEA'), season: 2013, stint: 3, stat_definition: StatDefinition.find_by_code('b.gp'), value: 38},
	{player: p, team: Team.find_by_abbr('SEA'), season: 2013, stint: 3, stat_definition: StatDefinition.find_by_code('b.pa'), value: 168},
	{player: p, team: Team.find_by_abbr('SEA'), season: 2013, stint: 3, stat_definition: StatDefinition.find_by_code('b.ab'), value: 152},
	{player: p, team: Team.find_by_abbr('SEA'), season: 2013, stint: 3, stat_definition: StatDefinition.find_by_code('b.r'), value: 21},
	{player: p, team: Team.find_by_abbr('SEA'), season: 2013, stint: 3, stat_definition: StatDefinition.find_by_code('b.h'), value: 39},
	{player: p, team: Team.find_by_abbr('SEA'), season: 2013, stint: 3, stat_definition: StatDefinition.find_by_code('b.2b'), value: 8},
	{player: p, team: Team.find_by_abbr('SEA'), season: 2013, stint: 3, stat_definition: StatDefinition.find_by_code('b.3b'), value: 4},
	{player: p, team: Team.find_by_abbr('SEA'), season: 2013, stint: 3, stat_definition: StatDefinition.find_by_code('b.hr'), value: 2},
	{player: p, team: Team.find_by_abbr('SEA'), season: 2013, stint: 3, stat_definition: StatDefinition.find_by_code('b.rbi'), value: 18},
	{player: p, team: Team.find_by_abbr('SEA'), season: 2013, stint: 3, stat_definition: StatDefinition.find_by_code('b.so'), value: 28},
	{player: p, team: Team.find_by_abbr('SEA'), season: 2013, stint: 3, stat_definition: StatDefinition.find_by_code('b.bb'), value: 16},
	{player: p, team: Team.find_by_abbr('SEA'), season: 2013, stint: 3, stat_definition: StatDefinition.find_by_code('b.gdp'), value: 1},
	{player: p, team: Team.find_by_abbr('SEA'), season: 2013, stint: 3, stat_definition: StatDefinition.find_by_code('b.hbp'), value: 0},
	{player: p, team: Team.find_by_abbr('SEA'), season: 2013, stint: 3, stat_definition: StatDefinition.find_by_code('b.sh'), value: 0},
	{player: p, team: Team.find_by_abbr('SEA'), season: 2013, stint: 3, stat_definition: StatDefinition.find_by_code('b.sf'), value: 0},
	{player: p, team: Team.find_by_abbr('SEA'), season: 2013, stint: 3, stat_definition: StatDefinition.find_by_code('b.ibb'), value: 0},
])
